name: Analyze tests

on:
  workflow_dispatch:

jobs:
  analyze-tests:
    runs-on: ubuntu-latest
    name: Run Essentia-enabled tests (optional)
    steps:
      - uses: actions/checkout@v4

      - name: Set up conda/mamba environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.analyze-cpu.yml
          activate-environment: songshare-analyze-cpu
          auto-update-conda: true
          use-mamba: true

      - name: Install project dependencies
        run: |
          poetry install

      - name: Run analyze tests
        run: |
          pytest -q -m essentia
